### ISSUE TITLE
Add Footer Component

### ISSUE THREAD

**Issue by sergomen** [sergomen/pomogoo#6]

**Comment by shivam-1810** [comment]
@sergomen Can you please assign this issue to me?

**Comment by sivasuriyankumarasamy** [comment]
Hi @sergomen ,

I would like to work on this issue. can you assign this to me

**Comment by sergomen** [comment]
Hi @sivasuriyankumarasamy,

I assigned. Good luck in completing the task.

**Comment by Pawankalyan2023** [comment]
hey bro , can I still work on this as this issue doesnt made any PR till now! @sergomen

**Comment by sergomen** [comment]
Hi @Pawankalyan2023.
Go ahead!
